import type { Metadata } from "next";
import { Inter , Lalezar } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] });

const lalezar = Lalezar({
  weight: "400",
  subsets: ["latin"],

  variable: "--font-lalezar",
});

export const metadata: Metadata = {
  title: "Lawyer",
  description: "Generated by rexcode",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={lalezar.variable}>
        <Navbar/>
        <main>
          {children}
        </main>
         <Footer/>
      </body>
    </html>
  );
}
